name: StartServer

on:
  repository_dispatch:
    types: ServerStart
  workflow_dispatch:
    
jobs:
  StartServer:
    runs-on: ubuntu-latest
    name: JellyfinServer
    continue-on-error: true
    steps:
      - uses: browser-actions/setup-firefox@latest
      - run: |
          sudo apt-get install -y xvfb
          sudo apt-get install firefox-geckodriver
          Xvfb -ac :99 -screen 0 1280x1024x16 & export DISPLAY=:99
          firefox --version
          firefox --new-window --headless https://google.com
