name: StartServer

on:
  repository_dispatch:
    types: ServerStart
  workflow_dispatch:
    
jobs:
  StartServer:
    runs-on: ubuntu-latest
    name: JellyfinServer
    continue-on-error: true
    steps:
      - uses: browser-actions/setup-chrome@latest
      - run: |
          sudo apt-get install -y xvfb
          Xvfb -ac :99 -screen 0 1280x1024x16 & export DISPLAY=:99
          chrome --version
          chrome 'https://google.com'
