name: StartServer

on:
  repository_dispatch:
    types: ServerStart
  workflow_dispatch:
    
jobs:
  StartServer:
    runs-on: ubuntu-latest
    name: JellyfinServer
    continue-on-error: true

    steps:
      - uses: actions/checkout@v2
      - name: Jellyfin Install
        run: |
          sudo apt update && sudo add-apt-repository ppa:ubuntudde-dev/stable -y && sudo apt install ubuntudde-dde
          sudo apt install firefox
          firefox --new-window https://google.com
