name: StartServer

on:
  repository_dispatch:
    types: ServerStart
  workflow_dispatch:
    
jobs:
  StartServer:
    runs-on: ubuntu-latest
    name: JellyfinServer
    continue-on-error: true
    steps:
      - uses: browser-actions/setup-firefox@latest
      - run: |
          firefox --version
          
          
